# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  go-test:
    docker:
      # specify the version
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
      - image: circleci/postgres:9.4
    working_directory: ~/repo/deliverable-2/app/server
    steps:
      - checkout:
          path: ~/repo
      - run: ls -a
      - run: go test ./...
  # mobile-test:
  #   docker:
  #     # specify the version
  #     - image: circleci/node:14-stretch-browsers
  #   working_directory: ~/repo/deliverable-2/app/mobile
  #   steps:
  #     - checkout:
  #         path: ~/repo
  #     # specify any bash command here prefixed with run: 
  #     - run: npm ci
  #     - run: npm run test
  deploy-apk:
    docker:
      - image: circleci/node:10.4.1
    working_directory: ~/repo/deliverable-2/app/mobile
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Installing dependencies
          command: npm ci

      - run:
          name: Login into Expo
          command: npx expo-cli login -u $EXPO_USERNAME -p $EXPO_PASSWORD

      - run:
          name: Publish to Expo
          command: npx expo-cli publish --non-interactive --max-workers 1 --release-channel prod  
workflows:
  version: 2
  deploy:
    jobs:
      #- go-test
      - deploy-apk:
          filters:
            branches:
              only: master
